In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("aids_attendance.xlsx")
display(df.head())

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW23AD50,SRAJAN S,Data Science & GenAI - 3nd Yr- AI&DS,11,0,11,0,0%,Critical,33 more,Never,11
1,4MW24AD001,ADITHYA S POOJARY,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0,64%,Critical,5 more,2026-10-07,0
2,4MW24AD002,ANKITHA PRASANNA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0,100%,Safe,✓ Met,2026-10-07,0
3,4MW24AD003,ANUSHA KOTEGAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
4,4MW24AD004,ANVITA RAMESH NAIK,Data Science & GenAI - 3nd Yr- AI&DS,11,9,2,0,82%,Warning,✓ Met,2026-10-07,0

In [3]:
print("First 10 rows:")
display(df.head(10))

print("Shape:", df.shape)

print("Data types:")
print(df.dtypes)

First 10 rows:

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW23AD50,SRAJAN S,Data Science & GenAI - 3nd Yr- AI&DS,11,0,11,0,0%,Critical,33 more,Never,11
1,4MW24AD001,ADITHYA S POOJARY,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0,64%,Critical,5 more,2026-10-07,0
2,4MW24AD002,ANKITHA PRASANNA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0,100%,Safe,✓ Met,2026-10-07,0
3,4MW24AD003,ANUSHA KOTEGAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
4,4MW24AD004,ANVITA RAMESH NAIK,Data Science & GenAI - 3nd Yr- AI&DS,11,9,2,0,82%,Warning,✓ Met,2026-10-07,0
5,4MW24AD005,ARPITHA M THANTRY,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73%,Critical,1 more,2026-10-07,0
6,4MW24AD007,ASNIYA,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
7,4MW24AD008,B. G PRARTHANA HEBBAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
8,4MW24AD009,BHARATHRAJ A NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,4,7,0,36%,Critical,17 more,2026-10-05,1
9,4MW24AD010,BHEEMA KATTIMANI,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73%,Critical,1 more,2026-10-07,0

Shape: (62, 12)
Data types:
Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [4]:
print(df.isnull().sum())

print("Never values in Last Present Date:")
print(
    df["Last Present Date"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("never")
    .sum()
)

Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64
Never values in Last Present Date:
5

In [5]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace("%", "pct", regex=False)
    .str.replace(r"[^a-z0-9]+", "_", regex=True)
    .str.strip("_")
)

print(df.columns.tolist())

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75pct', 'last_present_date', 'consecutive_absences']

In [6]:
df["attendance_pct"] = (
    df["attendance_pct"]
    .astype(str)
    .str.replace("%", "", regex=False)
    .astype(float)
)

df["last_present_date"] = pd.to_datetime(
    df["last_present_date"].replace("Never", pd.NA),
    errors="coerce"
)

display(df[["attendance_pct", "last_present_date"]].head())

   attendance_pct last_present_date
0             0.0               NaT
1            64.0        2026-10-07
2           100.0        2026-10-07
3            91.0        2026-10-07
4            82.0        2026-10-07